FROM python:3.10

WORKDIR /usr/app


RUN apt-get update
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .



EXPOSE 5001

# CMD ["python", "app.py"]
CMD ["flask", "--debug", "run", "--host=0.0.0.0", "--port=5001"]